package uz.attolabs.exception;

public class TaskException {
}
